### ISSUE TITLE
SMSRetriever.startWatch is not working

### ISSUE THREAD

**Issue by jineshh2** [andreszs/cordova-plugin-sms-retriever#6] opened 2020-07-01 07:37 UTC
Hi,

I tried to read SMS through API.
I tried your demo application but when i click startwatch at that time the msg display that SMS retriever started for 5 min but when SMS receive at that time no response from SMSRetriever.startWatch. so the onSMSArrive is also not calling.

Please check.

**Comment by elmy33** [comment] 2020-12-14 23:09
I reproduced this:
the error is happening in line:
smsRetrieverClient = SmsRetriever.getClient(cordova.getActivity().getApplicationContext());

![sms](https://user-images.githubusercontent.com/14844107/102146737-9021d280-3e7a-11eb-89a9-ba77368ac88f.jpg)

**Comment by elmy33** [comment] 2020-12-14 23:10
It happens when calling getHashString, but probably this is startWatch error also.

**Comment by elmy33** [comment] 2020-12-15 00:43
It can be fixed by setting "PLAY_SERVICES_VERSION": "15.0.1"

**Comment by himadridev** [comment] 2021-11-18 05:44
I am getting hash from `getHashString` and successfully started `startWatch`. With the same hash receiving SMS (as below format), but `onSMSArrive` not triggering.

With below dependencies,
`"cordova-android": "8.1.0"` 
`"cordova-support-google-services": "1.4.0"`
`"cordova-plugin-sms-retriever": "^1.0.9",` with `"PLAY_SERVICES_VERSION": "15.0.1"`

Please check if I am missing anything.

**Comment by andreszs** [comment] 2021-11-30 19:20
@iamhimadri Please retry with latest plugin **1.1.1**. You did well in using `PLAY_SERVICES_VERSION` 15 because the plugin now uses 15.0.0 also. Double check your **hashString**, I was mistaking a "I" with an "l" and once I fixed that it worked perfectly. Use console.log() to print the hash string, then copy-paste that hash.

The SMS can begin with either `<#>` or `[#]`, both are valid.

**Closed as completed** 2022-04-16 22:55 UTC
